#!/bin/bash

openocd -f /usr/local/share/openocd/scripts/interface/stlink-v2.cfg -f /usr/local/share/openocd/scripts/target/stm32f1x.cfg ;

# arm-none-eabi-gdb main.elf -iex "target remote localhost:3333"

